INSERT INTO products (name, description, price, stock, image, category) VALUES
('Kaos Polos Cotton Combed', 'Kaos polos bahan cotton combed 30s premium, adem dan menyerap keringat.', 45000, 150, 'product.jpg', 'Pakaian'),
('Kemeja Flanel Kotak-Kotak', 'Kemeja flanel lengan panjang cocok untuk gaya kasual sehari-hari.', 125000, 65, 'product.jpg', 'Pakaian'),
('Celana Chino Panjang', 'Celana chino stretch slim fit, nyaman digunakan untuk kerja atau santai.', 140000, 80, 'product.jpg', 'Pakaian'),
('Jaket Bomber Waterproof', 'Jaket bomber dengan bahan luar taslan waterproof dan furing dalam tebal.', 185000, 40, 'product.jpg', 'Pakaian'),
('Sepatu Sneakers Kasual', 'Sepatu sneakers pria bahan kanvas dengan sol karet anti slip.', 210000, 35, 'product.jpg', 'Sepatu'),
('Sepatu Pantofel Kulit', 'Sepatu pantofel pria bahan kulit asli untuk acara formal.', 350000, 20, 'product.jpg', 'Sepatu'),
('Sandal Gunung Outdoor', 'Sandal gunung dengan tali webing kuat dan sol grip tangguh.', 75000, 90, 'product.jpg', 'Sepatu'),
('Tas Ransel Laptop 15 Inch', 'Tas ransel dilengkapi kompartemen laptop dan pelindung hujan (raincoat).', 195000, 55, 'product.jpg', 'Aksesoris'),
('Dompet Kulit Panjang', 'Dompet pria bahan kulit sapi dengan banyak slot kartu.', 90000, 110, 'product.jpg', 'Aksesoris'),
('Jam Tangan Analog Pria', 'Jam tangan analog water resistant dengan tali kulit cokelat.', 250000, 25, 'product.jpg', 'Aksesoris'),
('Topi Snapback Kasual', 'Topi snapback dengan border rapi, ukuran bisa diatur.', 350000, 70, 'product.jpg', 'Aksesoris'),
('Sabuk Kulit Otomatis', 'Sabuk pria dengan kepala gesper otomatis tanpa lubang.', 65000, 85, 'product.jpg', 'Aksesoris'),
('Kacamata Hitam UV400', 'Kacamata hitam anti radiasi UV, cocok untuk berkendara atau ke pantai.', 40000, 130, 'product.jpg', 'Aksesoris'),
('Earphone Bluetooth TWS', 'True Wireless Stereo dengan bass mantap dan baterai tahan 5 jam.', 150000, 45, 'product.jpg', 'Elektronik'),
('Powerbank 10000mAh Fast Charging', 'Powerbank kapasitas besar dengan fitur pengisian daya cepat 20W.', 120000, 60, 'product.jpg', 'Elektronik'),
('Mouse Wireless Silent Click', 'Mouse wireless tanpa suara klik, desain ergonomis.', 55000, 95, 'product.jpg', 'Elektronik'),
('Keyboard Mekanikal RGB', 'Keyboard mekanikal dengan switch biru dan lampu latar RGB.', 320000, 15, 'product.jpg', 'Elektronik'),
('Speaker Bluetooth Portable', 'Speaker portable tahan air dengan koneksi bluetooth stabil.', 175000, 30, 'product.jpg', 'Elektronik'),
('Kabel Data Type-C Nylon Braided', 'Kabel data kuat anti putus mendukung fast charging.', 15000, 300, 'product.jpg', 'Elektronik'),
('Charger Dinding Dual Port', 'Kepala charger dengan dua port USB cerdas untuk dua perangkat.', 35000, 140, 'product.jpg', 'Elektronik'),
('Lampu Meja Belajar LED', 'Lampu meja dengan kecerahan yang bisa diatur dan leher fleksibel.', 60000, 50, 'product.jpg', 'Elektronik'),
('Kipas Angin Mini USB', 'Kipas angin portable yang bisa diisi ulang, mudah dibawa.', 25000, 180, 'product.jpg', 'Elektronik'),
('Smartwatch Fitur Kesehatan', 'Jam tangan pintar penunjuk detak jantung, langkah kaki, dan notifikasi.', 299000, 22, 'product.jpg', 'Elektronik'),
('Blender Portable Juicer', 'Blender mini bertenaga baterai untuk membuat jus di mana saja.', 85000, 40, 'product.jpg', 'Peralatan Rumah'),
('Teko Listrik Stainless Steel 1.8L', 'Teko pemanas air otomatis mati saat mendidih.', 110000, 33, 'product.jpg', 'Peralatan Rumah'),
('Panci Anti Lengket Teflon', 'Panci penggorengan lapisan teflon diameter 24cm.', 95000, 48, 'product.jpg', 'Peralatan Rumah'),
('Pisau Dapur Set 5 in 1', 'Set pisau stainless steel tajam lengkap dengan talenan.', 50000, 75, 'product.jpg', 'Peralatan Rumah'),
('Kotak Makan Sekat Plastik', 'Kotak bekal makanan anti tumpah bpa free.', 20000, 220, 'product.jpg', 'Peralatan Rumah'),
('Botol Minum Termos 500ml', 'Termos stainless mampu menjaga suhu panas/dingin hingga 12 jam.', 65000, 105, 'product.jpg', 'Peralatan Rumah'),
('Rak Sepatu Susun Plastik', 'Rak sepatu portable gampang dibongkar pasang.', 45000, 60, 'product.jpg', 'Peralatan Rumah'),
('Gantungan Baju Hanger Isi 10', 'Hanger pakaian plastik tebal tidak mudah patah.', 18000, 400, 'product.jpg', 'Peralatan Rumah'),
('Keset Kaki Microfiber', 'Keset kaki sangat menyerap air dan lembut di kaki.', 15000, 250, 'product.jpg', 'Peralatan Rumah'),
('Sapu dan Pengki Set', 'Sapu lantai dengan bulu nilon halus beserta pengki penampung.', 30000, 90, 'product.jpg', 'Peralatan Rumah'),
('Buku Catatan Notebook A5', 'Buku tulis sampul keras bergaris isi 100 lembar.', 22000, 160, 'product.jpg', 'Alat Tulis'),
('Pulpen Gel Hitam Lusin', 'Satu kotak pulpen gel tinta hitam isi 12 pcs.', 25000, 120, 'product.jpg', 'Alat Tulis'),
('Pensil Warna 24 Warna', 'Set pensil warna kayu berkualitas untuk anak sekolah.', 35000, 85, 'product.jpg', 'Alat Tulis'),
('Stabilo Highlighter Set 4 Warna', 'Penanda teks warna neon terang tidak tembus kertas.', 18000, 140, 'product.jpg', 'Alat Tulis'),
('Gunting Kantor Stainless', 'Gunting kertas tajam dengan pegangan plastik nyaman.', 12000, 200, 'product.jpg', 'Alat Tulis'),
('Papan Tulis Whiteboard Kecil', 'Whiteboard ukuran 30x40cm gratis spidol dan penghapus.', 28000, 50, 'product.jpg', 'Alat Tulis'),
('Matras Yoga Anti Slip', 'Matras olahraga bahan eva tebal 6mm empuk.', 55000, 70, 'product.jpg', 'Olahraga'),
('Tali Skipping Digital', 'Tali lompat dengan penghitung putaran otomatis.', 35000, 110, 'product.jpg', 'Olahraga'),
('Dumbbell Plastik 2kg Sepasang', 'Beban tangan isi pasir besi luar plastik untuk olahraga rumah.', 40000, 45, 'product.jpg', 'Olahraga'),
('Jersey Bola Dry-Fit', 'Baju olahraga bahan kaos dry-fit cepat kering.', 50000, 130, 'product.jpg', 'Olahraga'),
('Kacamata Renang Anti Fog', 'Kacamata berenang dengan lapisan pelindung embun.', 30000, 85, 'product.jpg', 'Olahraga'),
('Sabun Mandi Cair Refill 450ml', 'Sabun antiseptik wangi segar membersihkan kuman.', 22000, 180, 'product.jpg', 'Kesehatan & Kecantikan'),
('Shampoo Anti Ketombe 170ml', 'Shampoo perawatan rambut sehat bebas ketombe.', 25000, 140, 'product.jpg', 'Kesehatan & Kecantikan'),
('Pasta Gigi Pemutih 190g', 'Pasta gigi perlindungan ganda gigi sensitif dan memutihkan.', 15000, 210, 'product.jpg', 'Kesehatan & Kecantikan'),
('Pelembab Wajah Aloe Vera Gel', 'Gel lidah buaya menenangkan kulit kemerahan dan melembabkan.', 38000, 95, 'product.jpg', 'Kesehatan & Kecantikan'),
('Sunscreen SPF 50 PA++++', 'Tabir surya ringan tanpa whitecast untuk perlindungan harian.', 60000, 65, 'product.jpg', 'Kesehatan & Kecantikan'),
('Masker Medis 3-Ply Isi 50', 'Satu kotak masker pelindung hidung dan mulut standar medis.', 15000, 500, 'product.jpg', 'Kesehatan & Kecantikan');